using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

public enum Category {
    Local = 0, // PROXIMITY_1
    Regional = 1, // PROXIMITY_2
    InterRegional = 2, // PROXIMITY_3
    Long = 3, // PROXIMITY_4
    Epic = 4 // PROXIMITY_5
}

[SuppressMessage("ReSharper", "InconsistentNaming")]
public readonly struct CardData : IEquatable<CardData> {
    internal readonly string cityA;
    internal readonly string cityB;
    internal readonly int cost;
    internal readonly int importancePoints;
    internal readonly Category category;

    public CardData(City cityA, City cityB, int cost, int importancePoints) {
        // Enforce deterministic order
        if (cityA.ID < cityB.ID) {
            this.cityA = cityA.Name;
            this.cityB = cityB.Name;
        }
        else {
            this.cityA = cityB.Name;
            this.cityB = cityA.Name;
        }

        this.cost = cost;
        this.importancePoints = importancePoints;
        category = CardConstants.GetCategory(cost);
    }

    public CardData(string cityA, string cityB, int cost, int importancePoints) {
        this.cityA = cityA;
        this.cityB = cityB;
        this.cost = cost;
        this.importancePoints = importancePoints;
        category = CardConstants.GetCategory(cost);
    }

    public bool Equals(CardData other) {
        return Equals(cityA, other.cityA) && Equals(cityB, other.cityB) && cost == other.cost &&
               importancePoints == other.importancePoints;
    }

    public override bool Equals(object obj) {
        return obj is CardData other && Equals(other);
    }

    public override int GetHashCode() {
        return HashCode.Combine(cityA, cityB, cost, importancePoints);
    }
}

public static class CardConstants {
    public static Category GetCategory(int cost) {
        if (cost < 8) return Category.Local;
        if (cost < 12) return Category.Regional;
        if (cost < 16) return Category.InterRegional;
        if (cost < 20) return Category.Long;

        return Category.Epic;
    }

    public static CardData[] GetCategoryCardData(CardData[] cards, Category category) {
        return cards.Where(c => c.category == category)
            .OrderByDescending(it => it.importancePoints)
            .ThenByDescending(it => it.cost)
            .ToArray();
    }

    public static readonly Dictionary<Category, CardData[]> CARD_BANK = new() {
        {
            Category.Local, new CardData[189] {
                new("Bucuresti", "Constanta", 7, 80),
                new("Iasi", "Suceava", 5, 77),
                new("Bucuresti", "Craiova", 7, 76),
                new("Bucuresti", "Pitesti", 4, 75),
                new("Ploiesti", "Craiova", 5, 74),
                new("Bucuresti", "Brasov", 5, 73),
                new("Bucuresti", "Galati", 7, 71),
                new("Cluj Napoca", "Oradea", 5, 71),
                new("Suceava", "Bacau", 5, 71),
                new("Iasi", "Galati", 7, 70),
                new("Timisoara", "Oradea", 7, 69),
                new("Ploiesti", "Galati", 6, 69),
                new("Iasi", "Piatra Neamt", 5, 68),
                new("Constanta", "Galati", 7, 67),
                new("Bacau", "Brasov", 7, 66),
                new("Bucuresti", "Buzau", 4, 66),
                new("Craiova", "Brasov", 7, 65),
                new("Cluj Napoca", "Baia Mare", 5, 65),
                new("Bacau", "Galati", 7, 64),
                new("Iasi", "Botosani", 4, 64),
                new("Pitesti", "Brasov", 4, 64),
                new("Pitesti", "Targu Mures", 7, 63),
                new("Bucuresti", "Slatina", 6, 63),
                new("Constanta", "Buzau", 7, 62),
                new("Ploiesti", "Sibiu", 6, 62),
                new("Craiova", "Targoviste", 4, 62),
                new("Brasov", "Targu Mures", 7, 61),
                new("Cluj Napoca", "Sibiu", 5, 61),
                new("Ploiesti", "Slatina", 4, 61),
                new("Bucuresti", "Ramnicu Valcea", 5, 60),
                new("Bucuresti", "Focsani", 6, 59),
                new("Bacau", "Buzau", 6, 59),
                new("Iasi", "Focsani", 7, 58),
                new("Craiova", "Buzau", 7, 58),
                new("Bacau", "Botosani", 6, 58),
                new("Oradea", "Baia Mare", 6, 58),
                new("Brasov", "Piatra Neamt", 6, 58),
                new("Cluj Napoca", "Deva", 5, 58),
                new("Targu Mures", "Piatra Neamt", 7, 57),
                new("Galati", "Targoviste", 7, 57),
                new("Oradea", "Arad", 5, 57),
                new("Ploiesti", "Focsani", 4, 57),
                new("Pitesti", "Buzau", 4, 57),
                new("Suceava", "Vaslui", 7, 56),
                new("Craiova", "Sibiu", 7, 56),
                new("Targu Mures", "Baia Mare", 7, 56),
                new("Timisoara", "Deva", 5, 56),
                new("Cluj Napoca", "Satu Mare", 5, 55),
                new("Brasov", "Buzau", 5, 55),
                new("Pitesti", "Sibiu", 4, 55),
                new("Ploiesti", "Alexandria", 5, 54),
                new("Craiova", "Deva", 7, 53),
                new("Ploiesti", "Targu Jiu", 6, 53),
                new("Brasov", "Sibiu", 5, 53),
                new("Galati", "Buzau", 4, 53),
                new("Iasi", "Miercurea Ciuc", 7, 52),
                new("Timisoara", "Alba Iulia", 7, 52),
                new("Brasov", "Slatina", 6, 52),
                new("Bucuresti", "Calarasi", 4, 52),
                new("Bacau", "Focsani", 4, 52),
                new("Craiova", "Ramnicu Valcea", 4, 52),
                new("Bucuresti", "Braila", 6, 51),
                new("Ploiesti", "Miercurea Ciuc", 6, 51),
                new("Oradea", "Deva", 6, 51),
                new("Cluj Napoca", "Miercurea Ciuc", 7, 50),
                new("Timisoara", "Targu Jiu", 7, 50),
                new("Ploiesti", "Calarasi", 6, 50),
                new("Pitesti", "Focsani", 6, 50),
                new("Targoviste", "Sibiu", 5, 50),
                new("Piatra Neamt", "Botosani", 4, 50),
                new("Targu Mures", "Deva", 6, 49),
                new("Ploiesti", "Braila", 5, 49),
                new("Brasov", "Ramnicu Valcea", 5, 49),
                new("Galati", "Vaslui", 5, 49),
                new("Suceava", "Bistrita", 6, 48),
                new("Pitesti", "Alba Iulia", 6, 48),
                new("Brasov", "Focsani", 6, 48),
                new("Targu Mures", "Ramnicu Valcea", 6, 48),
                new("Craiova", "Alexandria", 5, 48),
                new("Ploiesti", "Giurgiu", 4, 48),
                new("Constanta", "Calarasi", 4, 48),
                new("Oradea", "Satu Mare", 4, 48),
                new("Pitesti", "Alexandria", 7, 47),
                new("Constanta", "Braila", 6, 47),
                new("Suceava", "Miercurea Ciuc", 6, 47),
                new("Ploiesti", "Slobozia", 5, 47),
                new("Piatra Neamt", "Vaslui", 4, 47),
                new("Brasov", "Alba Iulia", 7, 46),
                new("Bacau", "Miercurea Ciuc", 4, 46),
                new("Pitesti", "Targu Jiu", 4, 46),
                new("Bucuresti", "Sfantu Gheorghe", 6, 45),
                new("Buzau", "Slatina", 6, 45),
                new("Targoviste", "Focsani", 5, 45),
                new("Constanta", "Slobozia", 4, 45),
                new("Targu Mures", "Alba Iulia", 4, 45),
                new("Bacau", "Braila", 7, 44),
                new("Pitesti", "Miercurea Ciuc", 7, 44),
                new("Piatra Neamt", "Focsani", 6, 44),
                new("Arad", "Deva", 5, 44),
                new("Targu Mures", "Targu Jiu", 7, 43),
                new("Targoviste", "Alba Iulia", 7, 43),
                new("Botosani", "Vaslui", 6, 43),
                new("Sibiu", "Slatina", 6, 43),
                new("Ploiesti", "Sfantu Gheorghe", 4, 43),
                new("Ploiesti", "Tulcea", 7, 42),
                new("Timisoara", "Drobeta Turnu Severin", 7, 42),
                new("Pitesti", "Braila", 7, 42),
                new("Craiova", "Giurgiu", 6, 42),
                new("Targoviste", "Alexandria", 6, 42),
                new("Buzau", "Ramnicu Valcea", 5, 42),
                new("Pitesti", "Giurgiu", 6, 41),
                new("Targoviste", "Targu Jiu", 5, 41),
                new("Targu Mures", "Miercurea Ciuc", 4, 41),
                new("Sibiu", "Deva", 4, 41),
                new("Craiova", "Resita", 7, 40),
                new("Pitesti", "Slobozia", 7, 40),
                new("Arad", "Alba Iulia", 7, 40),
                new("Constanta", "Tulcea", 4, 40),
                new("Brasov", "Giurgiu", 7, 39),
                new("Targoviste", "Miercurea Ciuc", 6, 39),
                new("Piatra Neamt", "Bistrita", 6, 39),
                new("Galati", "Calarasi", 5, 39),
                new("Craiova", "Drobeta Turnu Severin", 4, 39),
                new("Targoviste", "Calarasi", 7, 38),
                new("Buzau", "Alexandria", 7, 38),
                new("Bacau", "Sfantu Gheorghe", 6, 38),
                new("Pitesti", "Drobeta Turnu Severin", 6, 38),
                new("Baia Mare", "Bistrita", 4, 38),
                new("Deva", "Ramnicu Valcea", 7, 37),
                new("Targoviste", "Braila", 6, 37),
                new("Vaslui", "Focsani", 6, 37),
                new("Pitesti", "Sfantu Gheorghe", 5, 36),
                new("Targoviste", "Giurgiu", 5, 36),
                new("Galati", "Slobozia", 4, 36),
                new("Botosani", "Bistrita", 7, 35),
                new("Ramnicu Valcea", "Focsani", 7, 35),
                new("Targoviste", "Slobozia", 6, 35),
                new("Slatina", "Alexandria", 6, 35),
                new("Sibiu", "Targu Jiu", 4, 35),
                new("Botosani", "Miercurea Ciuc", 7, 34),
                new("Sibiu", "Bistrita", 6, 34),
                new("Targu Mures", "Zalau", 5, 34),
                new("Buzau", "Calarasi", 4, 34),
                new("Slatina", "Targu Jiu", 4, 34),
                new("Targoviste", "Drobeta Turnu Severin", 7, 33),
                new("Sibiu", "Miercurea Ciuc", 7, 33),
                new("Targu Mures", "Sfantu Gheorghe", 6, 33),
                new("Ramnicu Valcea", "Alba Iulia", 5, 33),
                new("Buzau", "Giurgiu", 6, 32),
                new("Deva", "Targu Jiu", 4, 32),
                new("Vaslui", "Miercurea Ciuc", 6, 31),
                new("Arad", "Resita", 5, 31),
                new("Targoviste", "Sfantu Gheorghe", 4, 31),
                new("Piatra Neamt", "Sfantu Gheorghe", 5, 30),
                new("Slatina", "Giurgiu", 7, 29),
                new("Vaslui", "Braila", 6, 29),
                new("Focsani", "Miercurea Ciuc", 7, 28),
                new("Satu Mare", "Bistrita", 6, 28),
                new("Alba Iulia", "Targu Jiu", 6, 28),
                new("Buzau", "Sfantu Gheorghe", 6, 27),
                new("Sibiu", "Drobeta Turnu Severin", 6, 27),
                new("Focsani", "Calarasi", 6, 27),
                new("Alba Iulia", "Bistrita", 6, 27),
                new("Sibiu", "Zalau", 7, 26),
                new("Ramnicu Valcea", "Giurgiu", 7, 26),
                new("Buzau", "Tulcea", 5, 26),
                new("Slatina", "Drobeta Turnu Severin", 5, 26),
                new("Sibiu", "Sfantu Gheorghe", 6, 25),
                new("Slatina", "Sfantu Gheorghe", 7, 24),
                new("Ramnicu Valcea", "Resita", 7, 24),
                new("Alexandria", "Calarasi", 7, 24),
                new("Deva", "Drobeta Turnu Severin", 6, 24),
                new("Focsani", "Slobozia", 5, 24),
                new("Deva", "Zalau", 7, 23),
                new("Bistrita", "Miercurea Ciuc", 6, 23),
                new("Ramnicu Valcea", "Drobeta Turnu Severin", 5, 23),
                new("Ramnicu Valcea", "Sfantu Gheorghe", 6, 21),
                new("Alexandria", "Slobozia", 6, 21),
                new("Focsani", "Sfantu Gheorghe", 5, 20),
                new("Focsani", "Tulcea", 5, 19),
                new("Alba Iulia", "Zalau", 5, 19),
                new("Targu Jiu", "Resita", 4, 19),
                new("Calarasi", "Braila", 4, 19),
                new("Calarasi", "Giurgiu", 6, 18),
                new("Bistrita", "Zalau", 5, 16),
                new("Giurgiu", "Slobozia", 5, 15),
                new("Calarasi", "Tulcea", 6, 12),
                new("Resita", "Drobeta Turnu Severin", 4, 11),
                new("Slobozia", "Tulcea", 5, 9),
            }
        }, {
            Category.Regional, new CardData[228] {
                new("Iasi", "Ploiesti", 11, 81),
                new("Ploiesti", "Cluj Napoca", 11, 79),
                new("Ploiesti", "Constanta", 9, 78),
                new("Bucuresti", "Bacau", 10, 77),
                new("Cluj Napoca", "Timisoara", 10, 76),
                new("Cluj Napoca", "Suceava", 9, 75),
                new("Ploiesti", "Bacau", 8, 75),
                new("Cluj Napoca", "Bacau", 11, 74),
                new("Bucuresti", "Targu Mures", 11, 72),
                new("Iasi", "Brasov", 10, 72),
                new("Cluj Napoca", "Pitesti", 9, 72),
                new("Iasi", "Targu Mures", 11, 71),
                new("Constanta", "Pitesti", 11, 71),
                new("Timisoara", "Craiova", 10, 71),
                new("Timisoara", "Pitesti", 11, 70),
                new("Cluj Napoca", "Brasov", 10, 70),
                new("Ploiesti", "Targu Mures", 9, 70),
                new("Bucuresti", "Piatra Neamt", 11, 69),
                new("Bacau", "Pitesti", 10, 68),
                new("Timisoara", "Targu Mures", 11, 67),
                new("Cluj Napoca", "Targoviste", 10, 67),
                new("Ploiesti", "Piatra Neamt", 9, 67),
                new("Suceava", "Brasov", 9, 67),
                new("Constanta", "Targoviste", 10, 66),
                new("Cluj Napoca", "Piatra Neamt", 9, 66),
                new("Suceava", "Targu Mures", 9, 66),
                new("Iasi", "Buzau", 9, 65),
                new("Bacau", "Targu Mures", 8, 65),
                new("Cluj Napoca", "Arad", 10, 64),
                new("Craiova", "Targu Mures", 10, 64),
                new("Bucuresti", "Sibiu", 8, 64),
                new("Craiova", "Galati", 11, 63),
                new("Bacau", "Targoviste", 9, 63),
                new("Cluj Napoca", "Botosani", 10, 62),
                new("Suceava", "Baia Mare", 10, 62),
                new("Pitesti", "Galati", 8, 62),
                new("Oradea", "Targu Mures", 8, 62),
                new("Cluj Napoca", "Slatina", 11, 60),
                new("Suceava", "Buzau", 11, 60),
                new("Ploiesti", "Vaslui", 10, 60),
                new("Pitesti", "Piatra Neamt", 10, 60),
                new("Brasov", "Galati", 9, 60),
                new("Ploiesti", "Deva", 10, 59),
                new("Timisoara", "Sibiu", 9, 59),
                new("Timisoara", "Slatina", 11, 58),
                new("Targu Mures", "Targoviste", 8, 58),
                new("Bacau", "Sibiu", 11, 57),
                new("Bucuresti", "Alba Iulia", 10, 57),
                new("Cluj Napoca", "Ramnicu Valcea", 8, 57),
                new("Galati", "Piatra Neamt", 9, 56),
                new("Targu Mures", "Arad", 11, 55),
                new("Timisoara", "Ramnicu Valcea", 10, 55),
                new("Constanta", "Focsani", 9, 55),
                new("Targoviste", "Piatra Neamt", 9, 55),
                new("Bucuresti", "Targu Jiu", 8, 55),
                new("Ploiesti", "Alba Iulia", 8, 55),
                new("Targu Mures", "Buzau", 11, 54),
                new("Oradea", "Sibiu", 10, 54),
                new("Brasov", "Botosani", 10, 54),
                new("Iasi", "Bistrita", 11, 53),
                new("Timisoara", "Satu Mare", 11, 53),
                new("Bacau", "Ramnicu Valcea", 11, 53),
                new("Targu Mures", "Botosani", 10, 53),
                new("Piatra Neamt", "Baia Mare", 10, 53),
                new("Suceava", "Focsani", 9, 53),
                new("Bucuresti", "Miercurea Ciuc", 8, 53),
                new("Galati", "Botosani", 11, 52),
                new("Constanta", "Alexandria", 10, 52),
                new("Cluj Napoca", "Targu Jiu", 9, 52),
                new("Pitesti", "Deva", 8, 52),
                new("Baia Mare", "Arad", 11, 51),
                new("Craiova", "Focsani", 9, 51),
                new("Brasov", "Vaslui", 9, 51),
                new("Targu Mures", "Slatina", 9, 51),
                new("Piatra Neamt", "Buzau", 8, 51),
                new("Targu Mures", "Vaslui", 10, 50),
                new("Galati", "Slatina", 10, 50),
                new("Brasov", "Deva", 9, 50),
                new("Iasi", "Braila", 8, 50),
                new("Baia Mare", "Botosani", 11, 49),
                new("Piatra Neamt", "Sibiu", 10, 49),
                new("Craiova", "Alba Iulia", 9, 49),
                new("Iasi", "Slobozia", 11, 48),
                new("Targoviste", "Vaslui", 11, 48),
                new("Baia Mare", "Sibiu", 10, 48),
                new("Targu Mures", "Focsani", 11, 47),
                new("Bucuresti", "Drobeta Turnu Severin", 10, 47),
                new("Galati", "Ramnicu Valcea", 9, 47),
                new("Targoviste", "Deva", 9, 47),
                new("Arad", "Sibiu", 9, 47),
                new("Bacau", "Bistrita", 8, 47),
                new("Oradea", "Alba Iulia", 8, 47),
                new("Ploiesti", "Resita", 10, 46),
                new("Constanta", "Giurgiu", 9, 46),
                new("Targu Mures", "Satu Mare", 8, 46),
                new("Buzau", "Sibiu", 8, 46),
                new("Piatra Neamt", "Ramnicu Valcea", 11, 45),
                new("Bacau", "Calarasi", 10, 45),
                new("Craiova", "Miercurea Ciuc", 10, 45),
                new("Pitesti", "Bistrita", 10, 45),
                new("Oradea", "Targu Jiu", 10, 45),
                new("Baia Mare", "Deva", 10, 45),
                new("Ploiesti", "Drobeta Turnu Severin", 8, 45),
                new("Brasov", "Alexandria", 8, 45),
                new("Cluj Napoca", "Drobeta Turnu Severin", 11, 44),
                new("Craiova", "Calarasi", 11, 44),
                new("Iasi", "Sfantu Gheorghe", 9, 44),
                new("Bucuresti", "Tulcea", 8, 44),
                new("Oradea", "Bistrita", 8, 44),
                new("Brasov", "Targu Jiu", 8, 44),
                new("Buzau", "Vaslui", 8, 44),
                new("Iasi", "Tulcea", 10, 43),
                new("Craiova", "Braila", 10, 43),
                new("Galati", "Alexandria", 10, 43),
                new("Brasov", "Bistrita", 9, 43),
                new("Pitesti", "Calarasi", 8, 43),
                new("Piatra Neamt", "Alba Iulia", 11, 42),
                new("Cluj Napoca", "Sfantu Gheorghe", 9, 42),
                new("Bacau", "Slobozia", 9, 42),
                new("Timisoara", "Zalau", 10, 41),
                new("Craiova", "Slobozia", 10, 41),
                new("Brasov", "Calarasi", 9, 41),
                new("Arad", "Satu Mare", 9, 41),
                new("Baia Mare", "Alba Iulia", 8, 41),
                new("Suceava", "Zalau", 11, 40),
                new("Targoviste", "Bistrita", 11, 40),
                new("Galati", "Miercurea Ciuc", 10, 40),
                new("Botosani", "Focsani", 10, 40),
                new("Brasov", "Braila", 8, 40),
                new("Slatina", "Deva", 8, 40),
                new("Buzau", "Alba Iulia", 10, 39),
                new("Sibiu", "Focsani", 10, 39),
                new("Suceava", "Sfantu Gheorghe", 8, 39),
                new("Pitesti", "Resita", 8, 39),
                new("Oradea", "Resita", 10, 38),
                new("Sibiu", "Satu Mare", 10, 38),
                new("Arad", "Targu Jiu", 9, 38),
                new("Brasov", "Slobozia", 8, 38),
                new("Slatina", "Focsani", 8, 38),
                new("Pitesti", "Zalau", 11, 37),
                new("Baia Mare", "Miercurea Ciuc", 10, 37),
                new("Bacau", "Tulcea", 9, 37),
                new("Galati", "Giurgiu", 9, 37),
                new("Craiova", "Sfantu Gheorghe", 8, 37),
                new("Buzau", "Targu Jiu", 8, 37),
                new("Targu Mures", "Resita", 11, 36),
                new("Sibiu", "Alexandria", 11, 36),
                new("Brasov", "Drobeta Turnu Severin", 10, 36),
                new("Piatra Neamt", "Braila", 9, 36),
                new("Slatina", "Alba Iulia", 8, 36),
                new("Deva", "Satu Mare", 10, 35),
                new("Pitesti", "Tulcea", 9, 35),
                new("Targu Mures", "Drobeta Turnu Severin", 9, 35),
                new("Buzau", "Miercurea Ciuc", 8, 35),
                new("Piatra Neamt", "Slobozia", 11, 34),
                new("Targoviste", "Resita", 9, 34),
                new("Brasov", "Tulcea", 10, 33),
                new("Vaslui", "Bistrita", 10, 32),
                new("Slatina", "Miercurea Ciuc", 9, 32),
                new("Galati", "Sfantu Gheorghe", 8, 32),
                new("Ramnicu Valcea", "Alexandria", 8, 32),
                new("Piatra Neamt", "Zalau", 11, 31),
                new("Sibiu", "Braila", 11, 31),
                new("Slatina", "Calarasi", 10, 31),
                new("Focsani", "Alexandria", 9, 31),
                new("Deva", "Bistrita", 8, 31),
                new("Satu Mare", "Alba Iulia", 8, 31),
                new("Sibiu", "Giurgiu", 10, 30),
                new("Vaslui", "Calarasi", 10, 30),
                new("Deva", "Miercurea Ciuc", 10, 30),
                new("Focsani", "Targu Jiu", 10, 30),
                new("Arad", "Drobeta Turnu Severin", 9, 30),
                new("Slatina", "Braila", 9, 30),
                new("Ramnicu Valcea", "Bistrita", 9, 30),
                new("Targoviste", "Tulcea", 8, 30),
                new("Piatra Neamt", "Tulcea", 11, 29),
                new("Sibiu", "Slobozia", 11, 29),
                new("Buzau", "Drobeta Turnu Severin", 10, 29),
                new("Arad", "Zalau", 8, 29),
                new("Ramnicu Valcea", "Miercurea Ciuc", 8, 29),
                new("Slatina", "Slobozia", 9, 28),
                new("Ramnicu Valcea", "Calarasi", 9, 28),
                new("Sibiu", "Resita", 8, 28),
                new("Vaslui", "Slobozia", 9, 27),
                new("Slatina", "Resita", 8, 27),
                new("Ramnicu Valcea", "Braila", 8, 27),
                new("Alexandria", "Targu Jiu", 8, 27),
                new("Botosani", "Sfantu Gheorghe", 9, 26),
                new("Alba Iulia", "Miercurea Ciuc", 8, 26),
                new("Alexandria", "Miercurea Ciuc", 11, 25),
                new("Targu Jiu", "Bistrita", 10, 25),
                new("Deva", "Resita", 8, 25),
                new("Ramnicu Valcea", "Slobozia", 8, 25),
                new("Focsani", "Giurgiu", 8, 25),
                new("Targu Jiu", "Miercurea Ciuc", 11, 24),
                new("Slatina", "Tulcea", 11, 23),
                new("Alexandria", "Braila", 9, 23),
                new("Vaslui", "Sfantu Gheorghe", 8, 23),
                new("Targu Jiu", "Braila", 11, 22),
                new("Deva", "Sfantu Gheorghe", 10, 22),
                new("Ramnicu Valcea", "Zalau", 10, 22),
                new("Vaslui", "Tulcea", 8, 22),
                new("Alba Iulia", "Resita", 10, 21),
                new("Targu Jiu", "Giurgiu", 9, 21),
                new("Targu Jiu", "Slobozia", 11, 20),
                new("Ramnicu Valcea", "Tulcea", 10, 20),
                new("Miercurea Ciuc", "Braila", 10, 20),
                new("Alba Iulia", "Drobeta Turnu Severin", 8, 20),
                new("Miercurea Ciuc", "Giurgiu", 10, 19),
                new("Alexandria", "Drobeta Turnu Severin", 9, 19),
                new("Miercurea Ciuc", "Slobozia", 11, 18),
                new("Alba Iulia", "Sfantu Gheorghe", 8, 18),
                new("Targu Jiu", "Zalau", 11, 17),
                new("Alexandria", "Sfantu Gheorghe", 9, 17),
                new("Braila", "Giurgiu", 8, 17),
                new("Alexandria", "Tulcea", 11, 16),
                new("Targu Jiu", "Sfantu Gheorghe", 9, 16),
                new("Miercurea Ciuc", "Zalau", 9, 15),
                new("Bistrita", "Sfantu Gheorghe", 8, 15),
                new("Calarasi", "Sfantu Gheorghe", 10, 13),
                new("Giurgiu", "Drobeta Turnu Severin", 10, 13),
                new("Braila", "Sfantu Gheorghe", 8, 12),
                new("Giurgiu", "Sfantu Gheorghe", 8, 11),
                new("Giurgiu", "Tulcea", 10, 10),
                new("Slobozia", "Sfantu Gheorghe", 9, 10),
                new("Drobeta Turnu Severin", "Sfantu Gheorghe", 11, 8),
                new("Zalau", "Sfantu Gheorghe", 11, 7),
                new("Sfantu Gheorghe", "Tulcea", 10, 5),
            }
        }, {
            Category.InterRegional, new CardData[200] {
                new("Bucuresti", "Iasi", 13, 83),
                new("Bucuresti", "Cluj Napoca", 13, 81),
                new("Iasi", "Cluj Napoca", 14, 80),
                new("Bucuresti", "Timisoara", 15, 79),
                new("Iasi", "Constanta", 14, 79),
                new("Bucuresti", "Suceava", 14, 78),
                new("Ploiesti", "Timisoara", 13, 77),
                new("Ploiesti", "Suceava", 12, 76),
                new("Iasi", "Pitesti", 13, 74),
                new("Constanta", "Bacau", 13, 73),
                new("Cluj Napoca", "Craiova", 12, 73),
                new("Constanta", "Craiova", 14, 72),
                new("Suceava", "Pitesti", 13, 69),
                new("Bacau", "Craiova", 13, 69),
                new("Iasi", "Targoviste", 12, 69),
                new("Constanta", "Brasov", 12, 69),
                new("Timisoara", "Brasov", 14, 68),
                new("Suceava", "Oradea", 14, 68),
                new("Iasi", "Baia Mare", 15, 67),
                new("Craiova", "Oradea", 13, 66),
                new("Bucuresti", "Botosani", 15, 65),
                new("Ploiesti", "Arad", 15, 65),
                new("Constanta", "Piatra Neamt", 15, 65),
                new("Pitesti", "Oradea", 14, 65),
                new("Timisoara", "Targoviste", 12, 65),
                new("Suceava", "Galati", 12, 65),
                new("Suceava", "Targoviste", 12, 64),
                new("Oradea", "Brasov", 15, 63),
                new("Iasi", "Sibiu", 14, 63),
                new("Ploiesti", "Botosani", 13, 63),
                new("Cluj Napoca", "Buzau", 13, 63),
                new("Timisoara", "Baia Mare", 13, 63),
                new("Iasi", "Slatina", 15, 62),
                new("Bucuresti", "Vaslui", 12, 62),
                new("Timisoara", "Buzau", 15, 61),
                new("Craiova", "Piatra Neamt", 13, 61),
                new("Bucuresti", "Deva", 12, 61),
                new("Bacau", "Baia Mare", 12, 61),
                new("Constanta", "Sibiu", 15, 60),
                new("Oradea", "Targoviste", 15, 60),
                new("Iasi", "Ramnicu Valcea", 14, 59),
                new("Pitesti", "Baia Mare", 14, 59),
                new("Oradea", "Piatra Neamt", 14, 59),
                new("Targu Mures", "Galati", 14, 59),
                new("Cluj Napoca", "Vaslui", 13, 59),
                new("Constanta", "Slatina", 13, 59),
                new("Craiova", "Arad", 12, 59),
                new("Pitesti", "Arad", 13, 58),
                new("Constanta", "Vaslui", 12, 58),
                new("Suceava", "Sibiu", 12, 58),
                new("Suceava", "Slatina", 15, 57),
                new("Brasov", "Baia Mare", 13, 57),
                new("Iasi", "Alba Iulia", 15, 56),
                new("Cluj Napoca", "Focsani", 14, 56),
                new("Pitesti", "Botosani", 14, 56),
                new("Brasov", "Arad", 14, 56),
                new("Constanta", "Ramnicu Valcea", 12, 56),
                new("Bacau", "Slatina", 12, 56),
                new("Oradea", "Botosani", 15, 55),
                new("Suceava", "Deva", 14, 55),
                new("Craiova", "Vaslui", 15, 54),
                new("Targoviste", "Baia Mare", 15, 54),
                new("Bucuresti", "Bistrita", 14, 54),
                new("Suceava", "Ramnicu Valcea", 14, 54),
                new("Bacau", "Deva", 14, 54),
                new("Oradea", "Slatina", 14, 53),
                new("Targoviste", "Arad", 14, 53),
                new("Pitesti", "Vaslui", 12, 53),
                new("Ploiesti", "Bistrita", 12, 52),
                new("Suceava", "Satu Mare", 12, 52),
                new("Constanta", "Targu Jiu", 15, 51),
                new("Timisoara", "Alexandria", 15, 51),
                new("Bacau", "Satu Mare", 14, 51),
                new("Targoviste", "Botosani", 13, 51),
                new("Iasi", "Calarasi", 12, 51),
                new("Suceava", "Alba Iulia", 12, 51),
                new("Galati", "Sibiu", 12, 51),
                new("Oradea", "Ramnicu Valcea", 13, 50),
                new("Bacau", "Alba Iulia", 12, 50),
                new("Iasi", "Giurgiu", 15, 49),
                new("Constanta", "Miercurea Ciuc", 15, 49),
                new("Pitesti", "Satu Mare", 14, 49),
                new("Timisoara", "Bistrita", 13, 49),
                new("Bacau", "Alexandria", 13, 49),
                new("Timisoara", "Miercurea Ciuc", 15, 48),
                new("Bacau", "Targu Jiu", 14, 48),
                new("Bucuresti", "Resita", 12, 48),
                new("Piatra Neamt", "Slatina", 12, 48),
                new("Cluj Napoca", "Giurgiu", 15, 47),
                new("Brasov", "Satu Mare", 15, 47),
                new("Buzau", "Botosani", 12, 47),
                new("Bucuresti", "Zalau", 15, 46),
                new("Suceava", "Calarasi", 15, 46),
                new("Baia Mare", "Vaslui", 14, 46),
                new("Craiova", "Bistrita", 13, 46),
                new("Piatra Neamt", "Deva", 13, 46),
                new("Arad", "Slatina", 13, 46),
                new("Cluj Napoca", "Resita", 13, 45),
                new("Botosani", "Sibiu", 13, 45),
                new("Suceava", "Braila", 12, 45),
                new("Targoviste", "Satu Mare", 15, 44),
                new("Targu Mures", "Alexandria", 14, 44),
                new("Galati", "Alba Iulia", 14, 44),
                new("Ploiesti", "Zalau", 13, 44),
                new("Baia Mare", "Ramnicu Valcea", 13, 44),
                new("Suceava", "Slobozia", 14, 43),
                new("Bacau", "Giurgiu", 12, 43),
                new("Oradea", "Miercurea Ciuc", 12, 43),
                new("Piatra Neamt", "Satu Mare", 12, 43),
                new("Arad", "Ramnicu Valcea", 12, 43),
                new("Buzau", "Deva", 12, 43),
                new("Botosani", "Deva", 15, 42),
                new("Sibiu", "Vaslui", 13, 42),
                new("Galati", "Targu Jiu", 12, 42),
                new("Galati", "Bistrita", 15, 41),
                new("Botosani", "Ramnicu Valcea", 15, 41),
                new("Piatra Neamt", "Alexandria", 14, 41),
                new("Slatina", "Vaslui", 14, 41),
                new("Constanta", "Sfantu Gheorghe", 13, 41),
                new("Timisoara", "Sfantu Gheorghe", 15, 40),
                new("Targu Mures", "Calarasi", 15, 40),
                new("Piatra Neamt", "Targu Jiu", 14, 40),
                new("Targu Mures", "Braila", 14, 39),
                new("Baia Mare", "Targu Jiu", 14, 39),
                new("Bacau", "Zalau", 13, 39),
                new("Botosani", "Satu Mare", 13, 39),
                new("Suceava", "Tulcea", 14, 38),
                new("Craiova", "Zalau", 14, 38),
                new("Targu Mures", "Giurgiu", 13, 38),
                new("Botosani", "Alba Iulia", 13, 38),
                new("Vaslui", "Ramnicu Valcea", 13, 38),
                new("Targu Mures", "Slobozia", 14, 37),
                new("Arad", "Bistrita", 13, 37),
                new("Oradea", "Drobeta Turnu Severin", 12, 37),
                new("Brasov", "Resita", 12, 37),
                new("Piatra Neamt", "Calarasi", 12, 37),
                new("Arad", "Miercurea Ciuc", 15, 36),
                new("Buzau", "Bistrita", 14, 36),
                new("Deva", "Focsani", 14, 36),
                new("Craiova", "Tulcea", 12, 36),
                new("Oradea", "Sfantu Gheorghe", 14, 35),
                new("Vaslui", "Alba Iulia", 14, 35),
                new("Piatra Neamt", "Giurgiu", 13, 35),
                new("Brasov", "Zalau", 12, 35),
                new("Vaslui", "Alexandria", 15, 34),
                new("Galati", "Drobeta Turnu Severin", 14, 34),
                new("Ramnicu Valcea", "Satu Mare", 13, 34),
                new("Slatina", "Bistrita", 12, 33),
                new("Deva", "Alexandria", 12, 33),
                new("Targoviste", "Zalau", 12, 32),
                new("Botosani", "Braila", 12, 32),
                new("Sibiu", "Calarasi", 12, 32),
                new("Focsani", "Alba Iulia", 12, 32),
                new("Botosani", "Slobozia", 15, 30),
                new("Buzau", "Resita", 12, 30),
                new("Satu Mare", "Targu Jiu", 14, 29),
                new("Alba Iulia", "Alexandria", 13, 29),
                new("Baia Mare", "Sfantu Gheorghe", 12, 29),
                new("Focsani", "Bistrita", 12, 29),
                new("Arad", "Sfantu Gheorghe", 15, 28),
                new("Buzau", "Zalau", 15, 28),
                new("Deva", "Braila", 15, 28),
                new("Vaslui", "Giurgiu", 14, 28),
                new("Deva", "Giurgiu", 13, 27),
                new("Botosani", "Zalau", 12, 27),
                new("Satu Mare", "Miercurea Ciuc", 12, 27),
                new("Deva", "Slobozia", 15, 26),
                new("Botosani", "Tulcea", 14, 25),
                new("Alba Iulia", "Calarasi", 14, 25),
                new("Slatina", "Zalau", 13, 25),
                new("Vaslui", "Zalau", 15, 24),
                new("Sibiu", "Tulcea", 13, 24),
                new("Alba Iulia", "Braila", 13, 24),
                new("Focsani", "Resita", 14, 23),
                new("Alba Iulia", "Giurgiu", 12, 23),
                new("Targu Jiu", "Calarasi", 12, 23),
                new("Satu Mare", "Resita", 14, 22),
                new("Alba Iulia", "Slobozia", 13, 22),
                new("Focsani", "Drobeta Turnu Severin", 12, 22),
                new("Bistrita", "Braila", 15, 21),
                new("Miercurea Ciuc", "Calarasi", 12, 21),
                new("Alexandria", "Resita", 12, 20),
                new("Satu Mare", "Sfantu Gheorghe", 14, 19),
                new("Bistrita", "Resita", 14, 18),
                new("Alba Iulia", "Tulcea", 15, 17),
                new("Miercurea Ciuc", "Resita", 15, 17),
                new("Bistrita", "Drobeta Turnu Severin", 12, 17),
                new("Miercurea Ciuc", "Drobeta Turnu Severin", 13, 16),
                new("Braila", "Resita", 15, 15),
                new("Calarasi", "Drobeta Turnu Severin", 14, 15),
                new("Targu Jiu", "Tulcea", 13, 15),
                new("Braila", "Drobeta Turnu Severin", 13, 14),
                new("Giurgiu", "Resita", 13, 14),
                new("Slobozia", "Resita", 15, 13),
                new("Miercurea Ciuc", "Tulcea", 12, 13),
                new("Slobozia", "Drobeta Turnu Severin", 13, 12),
                new("Resita", "Zalau", 13, 10),
                new("Resita", "Sfantu Gheorghe", 13, 9),
                new("Drobeta Turnu Severin", "Zalau", 13, 9),
                new("Drobeta Turnu Severin", "Tulcea", 15, 7),
            }
        }, {
            Category.Long, new CardData[102] {
                new("Iasi", "Craiova", 16, 75),
                new("Bucuresti", "Oradea", 18, 74),
                new("Constanta", "Suceava", 18, 74),
                new("Iasi", "Oradea", 19, 73),
                new("Timisoara", "Suceava", 19, 73),
                new("Timisoara", "Bacau", 19, 72),
                new("Ploiesti", "Oradea", 16, 72),
                new("Suceava", "Craiova", 16, 70),
                new("Bucuresti", "Baia Mare", 18, 68),
                new("Constanta", "Targu Mures", 18, 68),
                new("Cluj Napoca", "Galati", 17, 68),
                new("Bucuresti", "Arad", 17, 67),
                new("Bacau", "Oradea", 16, 67),
                new("Timisoara", "Galati", 19, 66),
                new("Ploiesti", "Baia Mare", 16, 66),
                new("Timisoara", "Piatra Neamt", 18, 64),
                new("Suceava", "Arad", 19, 61),
                new("Constanta", "Botosani", 18, 61),
                new("Bacau", "Arad", 19, 60),
                new("Iasi", "Deva", 17, 60),
                new("Craiova", "Baia Mare", 17, 60),
                new("Bucuresti", "Satu Mare", 18, 58),
                new("Constanta", "Deva", 19, 57),
                new("Iasi", "Satu Mare", 17, 57),
                new("Craiova", "Botosani", 17, 57),
                new("Oradea", "Buzau", 18, 56),
                new("Ploiesti", "Satu Mare", 16, 56),
                new("Galati", "Baia Mare", 19, 55),
                new("Iasi", "Alexandria", 16, 55),
                new("Iasi", "Targu Jiu", 17, 54),
                new("Timisoara", "Focsani", 17, 54),
                new("Constanta", "Alba Iulia", 17, 53),
                new("Cluj Napoca", "Alexandria", 16, 53),
                new("Oradea", "Vaslui", 18, 52),
                new("Piatra Neamt", "Arad", 18, 52),
                new("Baia Mare", "Buzau", 18, 50),
                new("Suceava", "Alexandria", 17, 50),
                new("Craiova", "Satu Mare", 17, 50),
                new("Oradea", "Focsani", 19, 49),
                new("Cluj Napoca", "Calarasi", 17, 49),
                new("Arad", "Buzau", 17, 49),
                new("Suceava", "Targu Jiu", 16, 49),
                new("Cluj Napoca", "Braila", 16, 48),
                new("Galati", "Deva", 16, 48),
                new("Timisoara", "Calarasi", 19, 47),
                new("Baia Mare", "Slatina", 16, 47),
                new("Iasi", "Drobeta Turnu Severin", 19, 46),
                new("Timisoara", "Braila", 18, 46),
                new("Oradea", "Alexandria", 18, 46),
                new("Cluj Napoca", "Slobozia", 16, 46),
                new("Iasi", "Zalau", 16, 45),
                new("Timisoara", "Giurgiu", 16, 45),
                new("Constanta", "Resita", 19, 44),
                new("Timisoara", "Slobozia", 18, 44),
                new("Suceava", "Giurgiu", 16, 44),
                new("Botosani", "Slatina", 16, 44),
                new("Constanta", "Drobeta Turnu Severin", 17, 43),
                new("Baia Mare", "Focsani", 16, 43),
                new("Arad", "Focsani", 19, 42),
                new("Cluj Napoca", "Tulcea", 18, 41),
                new("Suceava", "Drobeta Turnu Severin", 18, 41),
                new("Bacau", "Resita", 18, 41),
                new("Oradea", "Giurgiu", 19, 40),
                new("Buzau", "Satu Mare", 18, 40),
                new("Bacau", "Drobeta Turnu Severin", 16, 40),
                new("Arad", "Alexandria", 17, 39),
                new("Vaslui", "Deva", 16, 39),
                new("Botosani", "Alexandria", 18, 37),
                new("Slatina", "Satu Mare", 16, 37),
                new("Botosani", "Targu Jiu", 17, 36),
                new("Vaslui", "Satu Mare", 16, 36),
                new("Baia Mare", "Braila", 19, 35),
                new("Galati", "Resita", 16, 35),
                new("Galati", "Zalau", 19, 33),
                new("Piatra Neamt", "Resita", 18, 33),
                new("Arad", "Giurgiu", 18, 33),
                new("Focsani", "Satu Mare", 18, 33),
                new("Botosani", "Calarasi", 16, 33),
                new("Vaslui", "Targu Jiu", 16, 33),
                new("Targu Mures", "Tulcea", 16, 32),
                new("Piatra Neamt", "Drobeta Turnu Severin", 16, 32),
                new("Baia Mare", "Resita", 16, 32),
                new("Botosani", "Giurgiu", 17, 31),
                new("Baia Mare", "Drobeta Turnu Severin", 16, 31),
                new("Deva", "Calarasi", 16, 29),
                new("Botosani", "Drobeta Turnu Severin", 19, 28),
                new("Alexandria", "Bistrita", 17, 26),
                new("Vaslui", "Drobeta Turnu Severin", 18, 25),
                new("Bistrita", "Calarasi", 18, 22),
                new("Deva", "Tulcea", 17, 21),
                new("Focsani", "Zalau", 16, 21),
                new("Satu Mare", "Drobeta Turnu Severin", 16, 21),
                new("Bistrita", "Giurgiu", 16, 20),
                new("Bistrita", "Slobozia", 17, 19),
                new("Alexandria", "Zalau", 18, 18),
                new("Calarasi", "Resita", 16, 16),
                new("Calarasi", "Zalau", 19, 14),
                new("Bistrita", "Tulcea", 17, 14),
                new("Braila", "Zalau", 18, 13),
                new("Giurgiu", "Zalau", 17, 12),
                new("Slobozia", "Zalau", 18, 11),
                new("Resita", "Tulcea", 17, 8),
            }
        }, {
            Category.Epic, new CardData[42] {
                new("Iasi", "Timisoara", 22, 78),
                new("Cluj Napoca", "Constanta", 20, 77),
                new("Constanta", "Timisoara", 22, 75),
                new("Constanta", "Oradea", 25, 70),
                new("Iasi", "Arad", 22, 66),
                new("Constanta", "Baia Mare", 25, 64),
                new("Constanta", "Arad", 24, 63),
                new("Oradea", "Galati", 22, 61),
                new("Timisoara", "Botosani", 20, 60),
                new("Timisoara", "Vaslui", 21, 57),
                new("Constanta", "Satu Mare", 25, 54),
                new("Galati", "Arad", 21, 54),
                new("Constanta", "Bistrita", 21, 50),
                new("Arad", "Botosani", 20, 48),
                new("Iasi", "Resita", 21, 47),
                new("Galati", "Satu Mare", 21, 45),
                new("Arad", "Vaslui", 21, 45),
                new("Constanta", "Zalau", 22, 42),
                new("Oradea", "Calarasi", 22, 42),
                new("Suceava", "Resita", 20, 42),
                new("Oradea", "Braila", 21, 41),
                new("Baia Mare", "Alexandria", 21, 40),
                new("Oradea", "Slobozia", 21, 39),
                new("Timisoara", "Tulcea", 20, 39),
                new("Baia Mare", "Calarasi", 22, 36),
                new("Arad", "Calarasi", 21, 35),
                new("Oradea", "Tulcea", 23, 34),
                new("Baia Mare", "Giurgiu", 20, 34),
                new("Arad", "Braila", 20, 34),
                new("Baia Mare", "Slobozia", 21, 33),
                new("Arad", "Slobozia", 20, 32),
                new("Satu Mare", "Alexandria", 21, 30),
                new("Botosani", "Resita", 21, 29),
                new("Baia Mare", "Tulcea", 21, 28),
                new("Arad", "Tulcea", 22, 27),
                new("Satu Mare", "Calarasi", 22, 26),
                new("Vaslui", "Resita", 20, 26),
                new("Satu Mare", "Braila", 21, 25),
                new("Satu Mare", "Giurgiu", 20, 24),
                new("Satu Mare", "Slobozia", 21, 23),
                new("Satu Mare", "Tulcea", 23, 18),
                new("Zalau", "Tulcea", 20, 6),
            }
        },
    };
}
